### ISSUE TITLE
Every time showing "Please Login To see Profile"

### ISSUE THREAD

**Issue by playatanu** [Susmita-Dey/ProManager#4]
![Screenshot 2023-06-10 195856](https://github.com/Susmita-Dey/ProManager/assets/70248732/3ce94c71-f488-4974-87d2-5ff848ebc611)

### Every time showing login
you can add a loader or progress bar.

**Comment by Susmita-Dey** [comment]
Hello @playatanu Thanks for opening up this issue. I just checked and it seems like there's some issue with your internet connection. Kindly reload the page once. In my side, it's working fine and not showing that more than 1 second after signup.
